package org.gradle.builds.generators;

import org.gradle.builds.assemblers.CppSettings;
import org.gradle.builds.assemblers.Settings;
import org.gradle.builds.model.Build;

import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Path;

public class ReadmeGenerator implements Generator<Build> {
    @Override
    public void generate(Build build) throws IOException {
        Path readMe = build.getRootDir().resolve("README.md");
        Files.createDirectories(readMe.getParent());
        try (PrintWriter printWriter = new PrintWriter(Files.newBufferedWriter(readMe))) {
            printWriter.println("<!-- GENERATED FILE -->");
            Settings settings = build.getSettings();
            printWriter.println();
            printWriter.println("This build was generated by [build-builder](https://github.com/adammurdoch/build-builder)");

            printWriter.println();
            printWriter.println("- projects: " + settings.getProjectCount());
            printWriter.println("- source files per project: " + settings.getSourceFileCount());
            if (settings instanceof CppSettings) {
                CppSettings cppSettings = (CppSettings) settings;
                printWriter.println("- header files per project: " + cppSettings.getHeaders());
                printWriter.println("- macro includes: " + cppSettings.getMacroIncludes());
            }

            printWriter.println();
        }
    }
}
